spring:
  application:
    name: gateway-service
  config:
    import: file:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret:
server:
  port: 8080

rate-limiting:
  default-capacity: 50
  default-refill-tokens: 25
  default-window-seconds: 60